---
input-files:
  - table_of_contents.md
  - ./introduction/background.md
  - ./introduction/ideation.md
  - ./introduction/existing_solutions.md
  - ./introduction/approach_concept.md
  - ./introduction/aims_objectives.md
  - ./introduction/scope.md
  - ./market_research/applications_analysis.md
  - ./market_research/steeple_analysis.md
  - ./market_research/swot_analysis.md
  - ./market_research/product_space.md
  - ./market_research/defining_users.md
  - ./market_research/personas.md
  - ./market_research/stakeholders.md
  - ./design_modeling/early_sketches.md
  - ./design_modeling/scenarios.md
  - ./design_modeling/storyboards.md
  - ./design_modeling/low_fidelity_iter1.md
  - ./design_modeling/low_fidelity_iter2.md
  - ./design_modeling/medium_fidelity.md
  - ./design_modeling/high_fidelity.md
  - ./heuristic_evaluation/evaluation.md
  - ./user_testing/methodology.md
  - ./requirements_specifications/functional_requirements.md
  - ./requirements_specifications/nonfunctional_requirements.md
  - ./requirements_specifications/external_interfaces.md
  - ./requirements_specifications/specifications.md
  - ./requirements_specifications/technical_architecture.md
  - ./project_management/general_organisation.md
  - ./project_management/roles.md
  - ./project_management/planning.md
  - ./methodology_selfevaluation/discussion.md
  - ./ethics.md
  - conclusion.md
output-file: midterm_report.pdf

pdf-engine: xelatex
citeproc: true

metadata-file: ./settings/metadata.yaml

include-before-body: coverPage.md
include-after-body: appendix.md